import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as logs from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import { DB_CONFIG } from '../config';

interface DatabaseStackProps extends cdk.StackProps {
  vpc: ec2.Vpc;
  rdsSg: ec2.SecurityGroup;
}

/**
 * WeCircle RDS PostgreSQL 16 — isolated private subnets, Multi-AZ.
 *
 * Credentials are generated by CDK and stored in Secrets Manager at
 * `wecircle/rds-credentials` (JSON with host/port/username/password/dbname).
 *
 * Phase 5 migration path:
 *   1. pg_dump from current EC2 Postgres → pg_restore into this instance.
 *   2. Run `prisma migrate deploy` against the new endpoint.
 *   3. Build DATABASE_URL = postgres://<user>:<pass>@<DbEndpoint>:5432/wecircle
 *      and store it in SSM /wecircle/DATABASE_URL.
 *   4. Flip DNS (api.*) to the new ALB.
 */
export class DatabaseStack extends cdk.Stack {
  readonly instance: rds.DatabaseInstance;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    this.instance = new rds.DatabaseInstance(this, 'Postgres', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16,
      }),
      vpc: props.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [props.rdsSg],

      // t3.small covers current load comfortably; resize via snapshot restore
      // if CPU or memory becomes the bottleneck post-migration.
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.SMALL,
      ),

      databaseName: DB_CONFIG.name,
      port: DB_CONFIG.port,

      // CDK generates a strong random password and stores it in Secrets Manager.
      // The secret JSON shape: { host, port, username, password, dbname, engine }.
      credentials: rds.Credentials.fromGeneratedSecret('wecircle', {
        secretName: 'wecircle/rds-credentials',
      }),

      multiAz: DB_CONFIG.multiAz,
      storageType: rds.StorageType.GP3,
      allocatedStorage: DB_CONFIG.allocatedStorageGiB,
      maxAllocatedStorage: DB_CONFIG.maxAllocatedStorageGiB,
      storageEncrypted: true,

      backupRetention: cdk.Duration.days(DB_CONFIG.backupRetentionDays),
      preferredBackupWindow: '03:00-04:00',         // 05:00–06:00 EET (quiet hours)
      preferredMaintenanceWindow: 'Mon:04:00-Mon:05:00',
      autoMinorVersionUpgrade: true,

      enablePerformanceInsights: true,
      cloudwatchLogsExports: ['postgresql', 'upgrade'],
      cloudwatchLogsRetention: logs.RetentionDays.ONE_MONTH,

      // Real user data lives here — never delete on stack removal.
      deletionProtection: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // ── Stack outputs ────────────────────────────────────────────────────
    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.instance.dbInstanceEndpointAddress,
      description:
        'RDS writer endpoint — build DATABASE_URL from this + the rds-credentials secret',
    });
    new cdk.CfnOutput(this, 'DbSecretArn', {
      value: this.instance.secret!.secretArn,
      description: 'Secrets Manager ARN for DB credentials (host/port/user/pass/dbname)',
    });
    new cdk.CfnOutput(this, 'DbPort', {
      value: this.instance.dbInstanceEndpointPort,
    });
  }
}
