// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZBvrjuXQJXboAf4uwyrAmM4DKAG_f4I',
    appId: '1:1005017903116:web:daba5f4cf412600ea43e29',
    messagingSenderId: '1005017903116',
    projectId: 'wecircle-719e1',
    authDomain: 'wecircle-719e1.firebaseapp.com',
    storageBucket: 'wecircle-719e1.firebasestorage.app',
    measurementId: 'G-LEETJG3PDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEkPLzvbx6QjAf2Qnv4y6zGQNkIuf-UY',
    appId: '1:1005017903116:android:ebff3d018182b37ea43e29',
    messagingSenderId: '1005017903116',
    projectId: 'wecircle-719e1',
    storageBucket: 'wecircle-719e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrBmJqVAlVwG4Paf2UfEqn1tTJnTBNDg',
    appId: '1:1005017903116:ios:fb34f7934c9b3175a43e29',
    messagingSenderId: '1005017903116',
    projectId: 'wecircle-719e1',
    storageBucket: 'wecircle-719e1.firebasestorage.app',
    iosBundleId: 'com.example.wesal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrBmJqVAlVwG4Paf2UfEqn1tTJnTBNDg',
    appId: '1:1005017903116:ios:fb34f7934c9b3175a43e29',
    messagingSenderId: '1005017903116',
    projectId: 'wecircle-719e1',
    storageBucket: 'wecircle-719e1.firebasestorage.app',
    iosBundleId: 'com.example.wesal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZBvrjuXQJXboAf4uwyrAmM4DKAG_f4I',
    appId: '1:1005017903116:web:b1715114d8b3826ca43e29',
    messagingSenderId: '1005017903116',
    projectId: 'wecircle-719e1',
    authDomain: 'wecircle-719e1.firebaseapp.com',
    storageBucket: 'wecircle-719e1.firebasestorage.app',
    measurementId: 'G-DCH12YE0CC',
  );
}
